# docker-compose.yml (version satırını kaldırın)
services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network
  web:
    build: .
    container_name: django_app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./ml/models:/app/ml/models
      - ./media:/app/media
      - ./static:/app/static
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - mongodb
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
volumes:
  mongodb_data:
